set(VCPKG_TARGET_ARCHITECTURE aarch64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

#set(CMAKE_POLICY_DEFAULT_CMP0078 NEW)
#list(append VCPKG_CMAKE_FLAGS -DBOOST_CHARCONV_QUADMATH_SUPPORT=OFF)

