
set(VCPKG_COMMON_VARS_TO_PRINT
    CURRENT_BUILDTREES_DIR
    CURRENT_PACKAGES_DIR
    CURRENT_PORT_DIR
    CURRENT_INSTALLED_DIR
    DOWNLOADS
    PORT
    TARGET_TRIPLET
    VCPKG_CRT_LINKAGE
    VCPKG_LIBRARY_LINKAGE
    VCPKG_ROOT_DIR
    VCPKG_TARGET_ARCHITECTURE
    VCPKG_TOOLCHAIN
    TRIPLET_SYSTEM_ARCH
    BUILD_ARCH
    DEBUG_CONFIG
    RELEASE_CONFIG
    VCPKG_TARGET_IS_WINDOWS
    VCPKG_TARGET_IS_UWP
    VCPKG_TARGET_IS_LINUX
    VCPKG_TARGET_IS_OSX
    VCPKG_TARGET_IS_FREEBSD
    VCPKG_TARGET_IS_ANDROID
    VCPKG_TARGET_IS_MINGW
    VCPKG_TARGET_EXECUTABLE_SUFFIX
    VCPKG_TARGET_STATIC_LIBRARY_SUFFIX
    VCPKG_TARGET_SHARED_LIBRARY_SUFFIX
)

foreach(var_name IN LISTS VCPKG_COMMON_VARS_TO_PRINT)
    # Check if the variable is defined before printing (optional, but cleaner)
    # Note: message() with ${UNDEFINED_VAR} prints an empty string anyway
    #    message(STATUS "TOOLCHAIN: ${var_name}: ${${var_name}}")
endforeach()

# VCPKG_TARGET_ARCHITECTURE

string(REPLACE "-" ";" ARCH_PARTS ${VCPKG_TARGET_ARCHITECTURE})

list(GET ARCH_PARTS 0 _CPU)
list(GET ARCH_PARTS 1 _MODEL)
list(GET ARCH_PARTS 2 _SYSTEM)

include("${CMAKE_CURRENT_LIST_DIR}/${_CPU}.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/${_MODEL}.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/${_SYSTEM}.cmake")
